import { type ColDef } from "ag-grid-community";

const StudentColumnDefs: ColDef[] = [
  {
    headerName: "Registration ID",
    field: "registrationId",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "First name",
    field: "firstName",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Last name",
    field: "lastName",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Date of birth",
    field: "dateOfBirth",
    sortable: true,
    filter: "agDateColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
    valueFormatter: (params) => params.value ? new Date(params.value).toLocaleDateString() : '',
  },
  {
    headerName: "Email",
    field: "email",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 200,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Phone",
    field: "mobileNumber",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "School",
    field: "establishment",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Admission Date",
    field: "admissionDate",
    sortable: true,
    filter: "agDateColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
    valueFormatter: (params) => params.value ? new Date(params.value).toLocaleDateString() : '',
  },
  {
    headerName: "Gender",
    field: "gender",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 120,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "City",
    field: "city",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 120,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Actions",
    field: "actions",
    sortable: false,
    filter: false,
    resizable: false,
    minWidth: 150,
    maxWidth: 150,
    cellStyle: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
  },
];

export default StudentColumnDefs;