import { type ColDef } from "ag-grid-community";

const StudentColumnDefs: ColDef[] = [
  {
    headerName: "Registration ID",
    field: "admission_no",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Date d'inscription",
    field: "created_at",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Level",
    field: "class_name",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 120,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "First name",
    field: "firstname",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Last name",
    field: "lastname",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Date of birth",
    field: "dob",
    sortable: true,
    filter: "agDateColumnFilter",
    resizable: true,
    minWidth: 150,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Email",
    field: "email",
    sortable: true,
    filter: "agTextColumnFilter",
    resizable: true,
    minWidth: 200,
    flex: 1,
    cellStyle: { textAlign: "left" },
  },
  {
    headerName: "Actions",
    field: "actions",
    sortable: false,
    filter: false,
    resizable: false,
    minWidth: 150,
    maxWidth: 150,
    cellStyle: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
    },
  },
];

export default StudentColumnDefs;